"""Create Tables

Revision ID: 397c930c2bfd
Revises:
Create Date: 2024-02-10 14:06:45.066698
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397c930c2bfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clients',
        sa.Column('user_id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('batch', sa.Integer(), nullable=True),
        sa.Column('credit_limit', sa.Integer(), nullable=True),
        sa.Column('interest_rate', sa.Integer(), nullable=True),
        sa.Column('denied_reason', sa.String(), nullable=True),
        sa.Column('denied_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_table(
        'loans',
        sa.Column('loan_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('due_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('loan_amount', sa.Float(), nullable=True),
        sa.Column('tax', sa.Float(), nullable=True),
        sa.Column('due_amount', sa.Float(), nullable=True),
        sa.Column('amount_paid', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['clients.user_id'],
        ),
        sa.PrimaryKeyConstraint('loan_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('clients')
    # ### end Alembic commands ###
